### ISSUE TITLE
[🐛 BUG] - Main window can't be closed on MacOS

### ISSUE THREAD

**Issue by omartin** [alexkim205/G-Desktop-Suite#55]
**Describe the bug**
When trying to hide the main window  nothing happens and the window stays there.

**To Reproduce**
1. Click on the red close button in the title bar or use the shortcut CMD+w
2. Nothing happens

**Expected behavior**
The window should disappear but the app should still be running : if you hit the icon in the Dock the main window should re-appear.
This is the standard behavior on MacOS X

**G Desktop Suite:**
 - Version 0.2.1

**Platform:**
 - OS: MacOSX
 - Version [e.g. 10]

**Additional context**

**Comment by alexkim205** [comment]
This behavior is intentional and won't be fixed. The main window should not be able to be closed unless all other child windows (docs, sheets, other windows you may have opened from the main window) have been closed. If we were to let users close the main window, they would have no way of going back to the root drive folder to open other files. 

The feature you might be looking for is #56.

**Comment by omartin** [comment]
I look for both features CMD+H and CMD+W, I understand that you won't fix it but this is still the standard behavior on MacOS (hitting the close button and the action being ignored feels very much like a bug)

> If we were to let users close the main window, they would have no way of going back to the root drive folder to open other files.
Well no, just click the icon on the Dock and the window is back - it doesn't quit the app.

Pretty sure you will have the same request soon :-)
